---
name:   Tilemap Viewer              # The application display name
short:  Tilemap                     # A shortened name for reference
appid:  edu.cornell.gdiac.code3     # Application identifier for Mac, iOS, Android
suffix: G78B13A9

build:  build                       # The build directory (targets are each a subdirectory)
assets: assets                      # The folder with the game assets (do not list asset)
icon:   icon.png                    # The application icon

orientation: landscape              # The orientation for mobile devices

includes:                           # Root directory for angle brackets
    - source
    
sources:                            # The list of the source code files
    - source/*.cpp
    - source/*.h
    - source/Tile/*.cpp
    - source/Tile/*.h
    - source/Tilemap/*.cpp
    - source/Tilemap/*.h
    - source/Scene/*.cpp
    - source/Scene/*.h
    - source/Input/*.cpp
    - source/Input/*.h
    - source/Character/*.cpp
    - source/Character/*.h
    - source/Path/*.cpp
    - source/Path/*.h
    - source/Camera/*.cpp
    - source/Camera/*.h
    - source/GuardSet/*.h
    - source/GuardSet/Guard/*.h
    - source/ItemSet/*.h
    - source/ItemSet/Item/*.h
    - source/Level/*.h
    - source/Level/*.cpp

# This must be one of portrait, landscape, portrait-flipped, landscape-flipped,
targets:                        # The target platforms to build for
    - android                   # Android Studio
    - apple                     # XCode (note macOS and iOS use one project)
    - windows                   # Windows Sisual Studio
    - cmake                     # This supports all Desktop platform GBA5AF6 GBA5AF6 GA5CAA5 G13C6F4 GE0F210 G78B13A9
